
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package mine.ws;

import java.util.logging.Logger;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-22T15:54:28.954+05:30
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerSrvService",
                      portName = "CustomerSrv",
                      targetNamespace = "http://ws.mine",
                      wsdlLocation = "http://localhost:8080/JAXWS/services/CustomerSrv?wsdl",
                      endpointInterface = "mine.ws.CustomerSrv")
                      
public class CustomerSrvImpl implements CustomerSrv {

    private static final Logger LOG = Logger.getLogger(CustomerSrvImpl.class.getName());

    /* (non-Javadoc)
     * @see mine.ws.CustomerSrv#enquireCustomer(mine.bean.Customer  cust )*
     */
    public mine.bean.Customer enquireCustomer(mine.bean.Customer cust) { 
        LOG.info("Executing operation enquireCustomer");
        System.out.println(cust);
        try {
            mine.bean.Customer _return = new mine.bean.Customer();
            _return.setAadhaarId("AadhaarId1712807602");
            _return.setAnnualIncome(Long.valueOf(-1764826120425870023l));
            _return.setCountryOfBirth("CountryOfBirth541220422");
            _return.setDob(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-11-22T15:54:28.963+05:30"));
            _return.setName("Name271654897");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see mine.ws.CustomerSrv#createCustomer(mine.bean.Customer  cust )*
     */
    public java.lang.String createCustomer(mine.bean.Customer cust) { 
        LOG.info("Executing operation createCustomer");
        System.out.println(cust);
        try {
            java.lang.String _return = "_return232883788";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see mine.ws.CustomerSrv#findByAadhaarIdAsync(java.lang.String  aadhaarId )*
     */
    public Response<mine.ws.FindByAadhaarIdResponse> findByAadhaarIdAsync(java.lang.String aadhaarId) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see mine.ws.CustomerSrv#findByAadhaarIdAsync(java.lang.String  aadhaarId ,)AsyncHandler<mine.ws.FindByAadhaarIdResponse>  asyncHandler )*
     */
    public Future<?> findByAadhaarIdAsync(java.lang.String aadhaarId,AsyncHandler<mine.ws.FindByAadhaarIdResponse> asyncHandler) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see mine.ws.CustomerSrv#findByAadhaarId(java.lang.String  aadhaarId )*
     */
    public mine.bean.Customer findByAadhaarId(java.lang.String aadhaarId) { 
        LOG.info("Executing operation findByAadhaarId");
        System.out.println(aadhaarId);
        try {
            mine.bean.Customer _return = new mine.bean.Customer();
            _return.setAadhaarId("AadhaarId757703537");
            _return.setAnnualIncome(Long.valueOf(-7261053835672299728l));
            _return.setCountryOfBirth("CountryOfBirth-978543531");
            _return.setDob(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-11-22T15:54:28.965+05:30"));
            _return.setName("Name1493515248");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see mine.ws.CustomerSrv#updateCustomer(mine.bean.Customer  cust )*
     */
    public java.lang.String updateCustomer(mine.bean.Customer cust) { 
        LOG.info("Executing operation updateCustomer");
        System.out.println(cust);
        try {
            java.lang.String _return = "_return-2033493730";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
