<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.mine" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.mine" xmlns:intf="http://ws.mine" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://ws.mine" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="doQuickSort">
    <complexType>
     <sequence>
      <element maxOccurs="unbounded" name="inArray" type="xsd:int"/>
     </sequence>
    </complexType>
   </element>
   <element name="doQuickSortResponse">
    <complexType>
     <sequence>
      <element maxOccurs="unbounded" name="doQuickSortReturn" type="xsd:int"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="doQuickSortResponse">

      <wsdl:part element="impl:doQuickSortResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="doQuickSortRequest">

      <wsdl:part element="impl:doQuickSort" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="QuickSortJAXWS">

      <wsdl:operation name="doQuickSort">

         <wsdl:input message="impl:doQuickSortRequest" name="doQuickSortRequest">

       </wsdl:input>

         <wsdl:output message="impl:doQuickSortResponse" name="doQuickSortResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="QuickSortJAXWSSoapBinding" type="impl:QuickSortJAXWS">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="doQuickSort">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="doQuickSortRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="doQuickSortResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="QuickSortJAXWSService">

      <wsdl:port binding="impl:QuickSortJAXWSSoapBinding" name="QuickSortJAXWS">

         <wsdlsoap:address location="http://localhost:8080/WebserviceJAX-WS/services/QuickSortJAXWS"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
